### ISSUE TITLE
Cals2html : Param to not ignore @align/valign with default value

### ISSUE THREAD

**Issue by jimetevenard** [ELSGestion/els-sie-xsl-lib#4]
The `@align` et `@valign` are not converted to CSS when they are set to their default values. (Default values from params `$xslLib:cals2html.default-(tgroup / td/ th)-(v)align` )

**The should be a parameter to disable this behavior**, to allow `@align` and / or `@valign` being explicitely set to theirs default values.

We do not always know about the actual default value in the display/print context at the time a document is being transformed.

**This is related to _ELS-internal_ Issue SIETRAINPR-1172**

**Comment by mricaud** [comment]
Is there a reason why keeping those default values only when it's explicitly specified at entry level?
It might also be set at row level, tgroup level, table level and of course colspec level (for @align only)

I guess what we want here is to explicitly set this values in the output ignoring default HTML values of the rendering engine (browser or any other). It doesn't really depends on how the value has been computed (from entry or row or colspec, etc.)

**Comment by jimetevenard** [comment]
Hi @mricaud ,

> Is there a reason why keeping those default values only when it's explicitly specified at entry level?
> It might also be set at row level, tgroup level, table level and of course colspec level (for @align only)

No, you’re rigth, there is’nt.

> I guess what we want here is to explicitly set this values in the output ignoring default HTML values of the rendering engine (browser or any other).

Yes, you got it right.
In fact the is **no** default value in HTML. Most browsers (but not all) do implements a stylesheet derived from this https://www.w3.org/TR/2011/REC-CSS2-20110607/sample.html#q22.0

But, as it self-says, this is not a normative standard, only an « advice ».
And it sometimes can be overriden by the CSS of the website

> It doesn't really depends on how the value has been computed (from entry or row or colspec, etc.) 

 Absolutely, it doesn’t.
