### ISSUE TITLE
used function raising "is unused"

### ISSUE THREAD

**Issue by ahu-els** [ELSGestion/els-sie-xsl-lib#9]
Hello,

With schematron "checkXSLTstyle.sch", I had this error "[xslqual] Stylesheet function is unused" raised on : 

<xsl:function name="dali:myFunc" as="xs:boolean">
...
<xsl:if test="not(dali:myFunc())">

**Comment by mricaud** [comment]
Hi @ahu-els 
Please use this repo : https://github.com/mricaud/xslt-quality
You'll find the schematron here :
https://github.com/mricaud/xslt-quality/blob/master/src/main/sch/checkXSLTstyle.sch

This new schematron corrects the bug you are pointing.

I will remove this old version here.

**Comment by mricaud** [comment]
old version removed
